### ISSUE TITLE
Can you clarify the conflicting license definitions?

### ISSUE THREAD

**Issue by jrmarino** [cforler/Ada-Crypto-Library#6]
I'm having a small problem in determining what the license actually is.
On /README.md, it says the whole thing is LGPL v2.1.
On /COPYING, it says the whole thing is GPLv2
in the tests directory, the license is GMGPL (presumably meaning everything in there is a different license but conflicts with README.md)

So which ones are correct?

**Comment by jrmarino** [comment]
Also, for example, the header of source files says GPLv2, e.g.
https://github.com/cforler/Ada-Crypto-Library/blob/master/src/crypto-asymmetric-ecies.ads

I really hope a library is not licensed with full GPL.  That would be quick unfortunate and would greatly impede adoption.

**Comment by cforler** [comment]
The correct license is the GNAT Modified General Public License (GMGPL).

**Comment by cforler** [comment]
Sorry for the confusion.

**Comment by jrmarino** [comment]
cforler, thanks.  Would you mind committing the clarification to the repository?  Licensing is a serious issue and there can't be confusion on it.

**Comment by jrmarino** [comment]
ah, you already did, at least in the top directory.  (I didn't check source file headers)
